### ISSUE TITLE
Here is some code to convert questions to JSON format

### ISSUE THREAD

**Issue by derekxmartin** [Bishalsarang/Leetcode-Questions-Scraper#2]
https://gist.github.com/derekmartinjs/415934f3fa73daebfc823ec79a41c109

Link to the output:
https://gist.github.com/derekmartinjs/e71e81f1710d75c97de721d746bacea5

**Comment by Bishalsarang** [comment]
Nice job
You can translate the code into Python and make a PR and we may
Since we are converting into JSON, we may want to convert so that everything can be easily accessed.
For instance, we can make an array of objects with key {Input, Output, Explanation} for each test case rather than putting it into a single array.
![image](https://user-images.githubusercontent.com/11006583/135022813-d01d7379-7a1b-4287-a428-14ad357a0e55.png)

Maybe similar to this?
![image](https://user-images.githubusercontent.com/11006583/135023140-d136d0e2-f2d2-4448-93e6-ef96237134ad.png)

Also, see the constraint section . I think if the constraint is spanning across multiple lines, it is being put into an array. We can put it into a single string for each constraint. Or, if there are multiple strings we can have an array with multiple items.

**Comment by derekxmartin** [comment]
I love your thoughts here, i will take that up and circle back. Happy to find an approach that will yield a faster runtime too, just fleshed this ad box
